### ISSUE TITLE
Release version in a public maven repository (like maven central)

### ISSUE THREAD

**Issue by emilaleborn** [eu-digital-green-certificates/dgca-app-core-android#12]
## Feature description
dgca app core provides a decoder that is useful to others. It would be great if it was provided in an easy consumable format like an artifact in a public maven repository. 

## Problem and motivation
By using a public maven repo, it's easy for downstream dependencies to keep up to date with any bugfixes etc.

**Comment by daniel-eder** [comment]
The android verifier app Readme will provide instructions (currently available in the PR: https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/pull/42/files ) on how to include the app core in the build. When following these instructions the gradle build system will use your local copy of the app core.

**Comment by zollole** [comment]
I would also love to be able to use maven coordinates for the decoder dependency. For whatever reason, Android Studio refuses to be persuaded to look up the compiled library in my local maven repo. And including the app core into my java based app the way the DGCA verifier app does, requires me to re-write the build.grade dependencies section (to not rely on the buildSrc module for settings or version numbers).
