### ISSUE TITLE
Deps.json_validation_rhino declaration is missing

### ISSUE THREAD

**Issue by anskaal** [eu-digital-green-certificates/dgca-app-core-android#24]
## Describe the bug

Gradle build fails because `Deps.json_validation_rhino` is not declared in the buildSrc module.

## Expected behaviour

I expected that cloning and building the project from main would work.

## Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/1208437/121470934-2c0e4000-c9bf-11eb-9e54-307b03890ae9.png)

1. Clone repo
2. Open in Android Studio
3. Initial build fails

## Possible Fix

Add `json_validation_rhino` to Versions- and Dependencies-objects under buildSrc.

**Comment by oleksandrsarapulovgl** [comment]
Thank you for finding it @anskaal ! Prepared PR with the fix: https://github.com/eu-digital-green-certificates/dgca-app-core-android/pull/26
