### ISSUE TITLE
JSON schema version 1.3 validation

### ISSUE THREAD

**Issue by Yasser-R** [eu-digital-green-certificates/dgca-app-core-android#30]
## Your Question

* Source File: JsonSchema.kt (https://github.com/eu-digital-green-certificates/dgca-app-core-android/blob/63a1eb32cef65b8a4cfe2210dd58442cb1a8190f/decoder/src/main/java/dgca/verifier/app/decoder/JsonSchema.kt)
* Line(s): 120, 138
* Question: We saw that the schema got updated to support incomplete dates, as stated by the last json schema version 1.3. However the updated omitted fnt and gnt fields max length, that should be put to 80 instead of 50. Is this planned for the next release ? 
This is also true for EuDgcSchema.swift (https://github.com/eu-digital-green-certificates/dgca-app-core-ios/blob/main/Sources/SupportingFiles/EuDgcSchema.swift)

Thank you very much for your answer !

**Comment by SchulzeStTSI** [comment]
@Yasser-R Yes we prepared already the pull requests for it. 

https://github.com/eu-digital-green-certificates/dgca-app-core-android/pull/33/files

**Comment by oleksandrsarapulovgl** [comment]
@Yasser-R we merged the PR, so we can close the questions

**Comment by Yasser-R** [comment]
@oleksandrsarapulovgl When will the android core be updated to support schema 1.3 then ?

**Comment by oleksandrsarapulovgl** [comment]
It's already up to date with Schema 1.3. All related PR have been merged, and released prepared

**Comment by oleksandrsarapulovgl** [comment]
@Yasser-R
