### ISSUE TITLE
Date Time Support

### ISSUE THREAD

**Issue by SchulzeStTSI** [eu-digital-green-certificates/dgca-app-core-android#31]
Please relax all dates in the schema so that date times accepted as well. (e.g. vaccination date): 

![image](https://user-images.githubusercontent.com/67590336/122004546-d964c780-cdb4-11eb-87b0-c04b1bbf08f2.png)

Please add a unit test for the special cases. 

Test Code: https://github.com/eu-digital-green-certificates/dcc-quality-assurance/blob/6c5f94da95e1e96cc09660fac111c96e238042fb/PL/1.0.0/specialcases/VAC-12.png

**Comment by SchulzeStTSI** [comment]
Similiar to this:

https://github.com/eu-digital-green-certificates/dgca-app-core-ios/pull/63/files

https://github.com/eu-digital-green-certificates/dgca-app-core-android/pull/35/files

**Comment by oleksandrsarapulovgl** [comment]
@SchulzeStTSI I tested, and it works without any changes for me. Are you sure we need to do anything here?

**Comment by SchulzeStTSI** [comment]
@oleksandrsarapulovgl If it's supported no change more necessary.
