### ISSUE TITLE
Trimming JSON-fields for whitespaces

### ISSUE THREAD

**Issue by Hendrik-Schmidt-Schierhorn-TSI** [eu-digital-green-certificates/dgca-app-core-android#48]
## Current Implementation

Decoded JSON fields might contain whitespaces.
E.g. GR/EL QR Vaccination Codes in Field "mp"

## Suggested Enhancement

During the CBOR Deserialization, all fields must be trimmed for whitespaces.

**Comment by oleksandrsarapulovgl** [comment]
PR: https://github.com/eu-digital-green-certificates/dgca-app-core-android/pull/53
